### ISSUE TITLE
add simple DOM binding?

### ISSUE THREAD

**Issue by mark-hahn** [goodeggs/teacup#35]
Like many others I've been paying great attention to data-binding frameworks like angular, react, and knockout.

I just discovered mithril (http://lhorie.github.io/mithril), which is a very lightweight mvc data-binding framework.  What is the most interesting thing to me about mithril is that the templates are implemented as a DSL in plain javascript which are conceptually like teacup.  The DSL is quite inferior to teacup of course.

I want to combine mithril with teacup somehow.  I have a side-project waiting to use it.  Here are some random ideas ...

1) Issue a pull request to mithril that enables coffeescript and teacup to be used with as little change as needed to mithril and teacup.

2) Add mithril capabilities to teacup and copy everything that makes sense as literally as possible.

3) Steal the lightweight nature and philosophy of mithril but create an entirely new tool. 

I never care about popularity of a module (my drykup is proof),  I just want to do something worthwhile, useful, and fun.  For the fun part I'd like to do #3.

Anyone interested in helping?  I would use teacup as the base for the new product.  Any long-term connection to teacup would be left as a decision for the future.

**Comment by mark-hahn** [comment]
Well, it's been a year and I obviously never did what I claimed I was going to do.

> We've had some fun using Teacup with Rivets.

What are you using now?  I'm back in the market for a simple binding solution.

**Comment by hurrymaplelad** [comment]
Hey @mark-hahn, we're still using Rivets for most of our binding.  We like [what we've seen](https://github.com/goodeggs/faces/blob/master/src/components/app_header.cjsx) with React and cjsx.  Might give that a try next time we're in the market for a new stack.

**Comment by hurrymaplelad** [comment]
[space-pen](https://github.com/atom/space-pen) is another interesting alternative.

**Comment by mark-hahn** [comment]
Thanks.

I've been working on the GItHub Atom editor which used `space-pen` as the
default until recently when they switched to native components.  Space-pen
doesn't have bindings.  There is a new space-pen in the works.

I've been considering some lighter react alternatives.

**Comment by mark-hahn** [comment]
Have you looked at riotjs?  I'm trying to come up with a react-like solution that not only uses coffescript for code but also teacup for the template.  I might be able to fork riotjs to use teacup.  It already supports coffeescript.
